### ISSUE TITLE
Fix formatted data 

### ISSUE THREAD

**Issue by lynn43n** [BGU-ISE/Hype7#1]
![image](https://user-images.githubusercontent.com/38001905/158028119-f1c3227c-2eda-4611-b499-199011ebf356.png)
Notice row number 151 the values are not correct according to the columns

**Comment by LevyIfta** [comment]
these files should become a db soon (first priority). should fix it.
also excel displays data really badly. open the csv file with notepad to check the actual data.
if need urgent care, talk to me.
closing for now
