### ISSUE TITLE
Create filters: Group by top hashtag 

### ISSUE THREAD

**Issue by lynn43n** [BGU-ISE/Hype7#8]
The client wanted the option to view the top most used hashtags and when clicked, he will be able top videos that use this hashtag

**Comment by LevyIfta** [comment]
thats a ui feature. we still haven't started working on ui. if anything add it to the design file
if there is a definite reason to believe we need to have specific features in metric manager for it,  i will make a specified issue.
closing the issue.

**Comment by LevyIfta** [comment]
done afak
